fix(CI): disable ocamltest for MSVC builds
Currently MSVC CI fails because it can't find ocamltest:

```
Run eval $(tools/msvs-promote-path) ; make -j tests ;
/cygdrive/c/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/bin/HostX86/x86 moved to the front of $PATH
make -C testsuite all
make[1]: Entering directory '/cygdrive/d/a/ocaml/ocaml/testsuite'
Makefile:171: *** ocamltest not found in ../ocamltest.  Stop.
make[1]: *** [Makefile:165: all] Error 2
make[1]: Leaving directory '/cygdrive/d/a/ocaml/ocaml/testsuite'
make: *** [Makefile:927: tests] Error 2
Error: Process completed with exit code 2.
```

This seems to be because it needs to be manually enabled in the
configure script.  This patch just turns off the windows test suite.
Perhaps we need to think hard about our testing strategy for the
compiler, but this unblocks CI for the moment (it's no worse than the
present situation, where CI just fails outright, test suite or no test
suite.)